# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c27fd4e635fdea5b0528c9dd94fd9e52"
application_url = "https://biodiversity-contributions-background-specified.trycloudflare.com"
embedded = true
name = "Ai-colour-change"
handle = "ai-colour-change"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://biodiversity-contributions-background-specified.trycloudflare.com/auth/callback",
  "https://biodiversity-contributions-background-specified.trycloudflare.com/auth/shopify/callback",
  "https://biodiversity-contributions-background-specified.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "testingforappmattmurden.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
